DROP TABLE MEDICAMENTOS IF EXISTS;
CREATE TABLE MEDICAMENTOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
CODIGO INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
LABORATORIO VARCHAR(50) NOT NULL,
CANTIDAD INT NOT NULL,
PRECIO DECIMAL(7,2)
);

INSERT INTO MEDICAMENTOS VALUES(DEFAULT,123,'IBUPIRAC', 'BAYER', 10,350),
(DEFAULT,456,'ACETAMINOFEM', 'ABOUT', 15,400),(DEFAULT,789,'PARACETAMOL', 'PFIZER', 15,150);